version: '3.9'
services:
  keycloak:
    container_name: keycloak

    image: quay.io/keycloak/keycloak:latest
    ports:
      - "8080:8080"
      - "8443:8443" # For https version
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - type: bind
        source: "C:\\Users\\kminh\\AppData\\Local\\mkcert\\rootCA.pem"
        target: /opt/keycloak/bin/mkcert/rootCA.pem
      - type: bind
        source: "C:\\Users\\kminh\\AppData\\Local\\mkcert\\rootCA-key.pem"
        target: /opt/keycloak/bin/mkcert/rootCA-key.pem
    entrypoint: /bin/sh
    command:
      - -c
      # - /opt/keycloak/bin/kc.sh
      - "/opt/keycloak/bin/kc.sh --verbose start --hostname=localhost --https-certificate-file=/opt/keycloak/bin/mkcert/rootCA.pem --https-certificate-key-file=/opt/keycloak/bin/mkcert/rootCA-key.pem"
