database:
  user: hanko
  password: hanko
  database: hanko
  host: postgresd
  port: "5432"
  dialect: "postgres"
passcode:
  email:
    from_address: no-reply@hanko.io
  smtp:
    host: "mailslurper"
    port: "2500"
secrets:
  keys:
    - abcedfghijklmnopqrstuvwxyz
service:
  name: "Hanko Authentication Service"
webauthn:
  relying_party:
    id: "nothing"
    display_name: "Local Host"
    origins:
      - "https://localhost:3000"
server:
  public:
    address: ":8000"
    cors:
      allow_origins:
        - "https://github.com"
      unsafe_wildcard_origin_allowed: false
  admin:
    address: ":8001"

emails:
  require_verification: false